project:
  type: website
  output-dir: docs
title: "ME2491 Infectious Diseases"
website:
  sidebar:
    pinned: true
    style: "docked"
    search: true
    contents:
      - Index.qmd
      - Antibiotic.qmd
      - Resistance.qmd
      - Allergies.qmd
      - FUOpage.qmd
      - febrileneutropenia.qmd
      - IFI.qmd
      - Diarrheapage.qmd
      - Intraabdominal.qmd
      - Malariapage.qmd
format: 
  html:
    theme: journal
    css: styles.css
    toc: true
editor: visual

