project:
  type: website
  output-dir: docs
title: "Infectious Diseases"
website:
  sidebar:
    pinned: true
    style: "docked"
    search: true
    contents:
      - Index.qmd
      - Antibiotic.qmd
      - Allergies.qmd
    
format: 
  html:
    theme: journal
    css: styles.css
    toc: true
    include-before-body: translate.html
editor: visual

