project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!docs/"
    - "!diarrhea-handout.qmd"
  resources:
    - diarrhea-webpage.pdf
title: "Infectious Diseases"
website:
  sidebar:
    pinned: true
    style: "docked"
    search: true
    contents:
      - text: "Homepage"
        href: index.qmd
      - antibiotic-principles.qmd
      - allergies.qmd
      - fuo.qmd
      - intraabdominal.qmd
      - immunosuppression.qmd
      - febrile-neutropenia.qmd
      - diarrhea.qmd
      - malaria.qmd
      - ifi.qmd
      - section: "Study Guides"
        contents:
          - text: "Study Guide (English)"
            href: study-guide.qmd
          - text: "Guida allo Studio (Italiano)"
            href: guida-studio.qmd
    
bibliography:
  - refs-diarrhea.bib
  - refs-febrile-neutropenia.bib
  - refs-fuo.bib
  - refs-general.bib
  - refs-immunocompromise.bib
  - refs-intraabdominal-1.bib
  - refs-intraabdominal-2.bib
  - refs-malaria.bib
  - fungal-references.bib
csl: diagnostic-microbiology-and-infectious-disease.csl

format: 
  html:
    theme: journal
    css: styles.css
    toc: true
    include-before-body: translate.html
editor: visual

