project:
  type: website
  output-dir: docs
  resources:
    - chapter-draft_files/
title: "Infectious Diseases"
website:
  sidebar:
    pinned: true
    style: "docked"
    search: true
    contents:
      - Index.qmd
      - Antibiotic.qmd
      - Allergies.qmd
      - Intraabdominal.qmd
      - immunosuppression.qmd
      - febrileneutropenia.qmd
      - Diarrheapage.qmd
      - FUOpage.qmd
    
bibliography: diarrhea-references.bib
csl: diagnostic-microbiology-and-infectious-disease.csl

format: 
  html:
    theme: journal
    css: styles.css
    toc: true
    include-before-body: translate.html
editor: visual

