---
title: "Principles of Antibiotic Therapy"
format: html
editor: visual
---

## Slides

Web (HTML) version of lecture slides can be accessed [here](https://russlewisbo.github.io/antibiotictreatment/Principles_lecture.html#/principles-of-antibiotic-therapy)

PDF version of slides (interactive content will not work) can be accessed: [here](Antibiotic_principles_Lewis.pdf)

## Background reading

Although published in 2011, this paper remains the highest-cited general review on [Principles of Antibiotic Treatment](leekha.pdf)

[Classic Antibiotic PK/PD Review](drusano2004.pdf)

Some information out of date, but this is a [Classic Antibiotic PK/PD Review](craig.pdf) from the "father" of the field, Dr. William Craig, M.D.

[PK/PD and TDM Position Paper](Roberts2014.pdf)

[Recent review on antimicrobial susceptibiltiy testing methods](Wenzler2023.pdf)

[IDSA Clinical Microbiology Guidelines 2018](IDSA2018clinmicro.pdf)

[EUCAST Website](https://www.eucast.org/)

## Links to Prof. Sebastian Wicha's online precision antibiotic dosing models

Click on this link: [TDMx](http://www.tdmx.eu/Launch-TDMx/)

<br> *Note: The UNIPD Proxy may block the TDMx landing page for the models, but individual drug model pages demonstrated in class still seemed to be accessible through the proxy:*

[Gentamicin](http://52.17.60.199/Gentamicin1/) <br> [Vancomycin](https://tdmx.shinyapps.io/vancomycin/) <br> [Meropenem](https://tdmx.shinyapps.io/Meropenem/) <br>

## Lecture notes- Part 1

[📄 Download PDF version](Principles_lecture_handout.pdf){.btn .btn-primary target="_blank"}

<iframe src="Principles_handout_web.html" width="100%" height="900px" style="border: 1px solid #ddd; border-radius: 4px;" sandbox="allow-same-origin allow-scripts allow-downloads allow-forms">

</iframe>

## Lecture notes- Part 2

[📄 Download PDF version](Principles_handout_web_part2.pdf){.btn .btn-primary target="_blank"}

<iframe src="Principles_handout_web_part2.html" width="100%" height="900px" style="border: 1px solid #ddd; border-radius: 4px;" sandbox="allow-same-origin allow-scripts allow-downloads allow-forms">

</iframe>
